version: '3.7'

services:
# imagem customizada
  app:
    build: 
      args:
        user: higorzica
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: higorzica/laravel-app-image
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    restart: unless-stopped
    networks:
      - docker-laravel

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - docker-laravel
  
  # redis
  redis:
    image: redis:latest
    networks:
      - docker-laravel
  
  
    # db mysql
  db:
    image: mysql:5.7.22
    restart: unless-stopped
    environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_USER: ${DB_USERNAME}
    volumes:
        - ./.docker/mysql:/var/lib/mysql
    ports:
        - "3388:3306"
    networks:
        - docker-laravel


networks:
  docker-laravel:
    driver: bridge
    